#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    set ia_blocklist {
        type ipv4_addr
        flags timeout
        timeout 1h
        comment "Gestionado por ai_firewall.py"
    }

    chain input {
        type filter hook input priority 0;
        policy drop;

        iifname "lo" accept
        ct state established,related accept

        ip saddr @ia_blocklist counter drop

        tcp dport { 22, 80, 443 } accept
        ip protocol icmp limit rate 5/second accept

        counter log prefix "NFT-DROP: " flags all
        drop
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;

        ct state established,related accept

        ip saddr @ia_blocklist counter drop

        # Permitir ping controlado entre VM2 y VM3
        ip protocol icmp limit rate 5/second accept

        # Permitir desde VM2 Ubuntu atacante hacia VM3 servidor interno
        # enp0s8 = LAB_EXT / enp0s9 = LAB_LAN
        iifname "enp0s8" oifname "enp0s9" ip daddr 192.168.10.10 tcp dport { 22, 80, 443 } accept

        # Permitir respuestas desde VM3 hacia VM2
        iifname "enp0s9" oifname "enp0s8" ip saddr 192.168.10.10 accept

        counter log prefix "NFT-DROP: " flags all
        drop
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}
